<ul class="pagination">
	<li class="pager-item"><a href="<?php echo $this->url->display(array ('c'=>'index', 'a'=>'index', 'params'=>array())); ?>"><?php echo $this->translate->t('go back'); ?></a></li>
</ul>

<h1><?php echo $this->translate->t('read logs'); ?></h1>

<?php $items = $this->logsPaginator->items(); ?>
<?php if(!empty($items)): ?>

<a class="delete" href="<?php echo $this->url->display(array('c'=>'log', 'a'=>'vider')); ?>"><?php echo $this->translate->t('empty logs'); ?></a>

<div class="logs">
	<?php $this->logsPaginator->render('pagination.phtml','page'); ?>
	
	<?php foreach($items as $log) : ?>
	<div class="log <?php echo $log->level(); ?>"><span class="date"><?php echo date('d/m/Y - H:i:s', strtotime($log->date())); ?></span><?php echo $log->info(); ?></div>
	<?php endforeach; ?>
	
	<?php $this->logsPaginator->render('pagination.phtml','page'); ?>
</div>
<?php else: ?>
<p><?php echo $this->translate->t('logs empty'); ?></p>
<?php endif; ?>
