<!-- message d'accueil -->
<?php echo Translate::t ('page home', Configuration::VERSION); ?>

<?php if (isset ($this->error)) { ?>
<!-- affichage erreurs -->
<div class="error"><?php echo $this->error; ?></div>
<?php } ?>

<?php if (isset ($this->ok)) { ?>
<!-- affichage messages ok -->
<div class="ok"><?php echo $this->ok; ?></div>
<?php } ?>

<?php if ($this->user->isLogged ()) { ?>
	<p><?php echo Translate::t ('welcome', $this->user->id ()); ?> (<a href="<?php echo _url ('index', 'logout'); ?>"><?php echo Translate::t ('logout'); ?></a>)</p>
<?php } else { ?>
<!-- affichage formulaire -->
<form method="post" action="<?php echo _url ('index', 'login'); ?>">
	<fieldset>
		<legend><?php echo Translate::t ('connection'); ?></legend>
		<p>
			<label for="id"><?php echo Translate::t ('id'); ?></label>
			<input type="text" name="id" id="id" />

			<label></label>
			<input type="submit" value="<?php echo Translate::t ('connection'); ?>" />
		</p>
	</fieldset>
</form>
<?php } ?>
